services:
  - type: web
    name: neurofi-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    autoDeploy: true

  - type: worker
    name: neurofi-bot-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python Cryptobot.py
    autoDeploy: true
